''
'' swedbankpay theme based off of https://design.swedbankpay.com
''
'' Author = "Asbjørn Ulsberg"
'' Copyright (c) 2021 Swedbank Pay

!$THEME = "swedbankpay"

skinparam backgroundColor "transparent"
skinparam useBetaStyle false

!$black = "#222222"
!$text_gray = "#767676"
!$list_gray = "#999999"
!$light_gray = "#f9f8f6"
!$white = "#ffffff"
!$solid_brown = "#2f2424"
!$dark_brown = "#493c3b"
!$medium_brown = "#72605e"
!$soft_brown = "#a38b80"
!$light_brown = "#d4c4bc"

!$brand_primary = "#fdc129"
!$brand_primary_light = "#ffcc00"
!$brand_primary_light_2 = "#ffdf88"
!$brand_primary_light_3 = "#fff3d5"
!$brand_primary_faded = "fade(@brand_primary, 60%)"
!$brand_secondary_dark_1 = $dark_brown
!$brand_secondary_dark_2 = $solid_brown
!$brand_secondary = "#512b2b"
!$brand_secondary_light_1 = $medium_brown
!$brand_secondary_light_2 = $soft_brown
!$brand_secondary_light_3 = $light_brown
!$brand_secondary_light_4 = "#d4b8a3"
!$brand_secondary_info_1 = "#8acdc3"
!$brand_secondary_info_2 = "#efb7b6"
!$brand_tertiary = "#ee7023"
!$brand_accent = "#31a3ae"
!$brand_accent_links = "#257886"
!$brand_accent_disabled = "#98d0d6"

' Background Colors
!$brand_bg_1 = "#fbf2ea"
!$brand_bg_2 = "#ebf8f2"
!$brand_bg_3 = "#fbedf4"
!$brand_bg_4 = "#e9f7fb"
!$brand_bg_gray = "#ebe7e2"
!$brand_bg_white = "#ffffff"

' State colors
!$brand_success = "#437e15"
!$brand_success_light = "#f2f7eb"
!$brand_success_light_2 = "#99cc66"
!$brand_warning = "#f9ce22"
!$brand_warning_light = "#fff3d5"
!$brand_warning_2 = $brand_tertiary
!$brand_error_border = "#f1bbb9"
!$brand_error = "#c5131c"
!$brand_error_light = "#f9ded3"
!$brand_info = "#3e6ab6"
!$brand_info_light = "#e8eff9"

!$primary_text = $text_gray
!$secondary_text = $black
!$info_text = $black
!$success_text = $white
!$warning_text = $white
!$danger_text = $white

!procedure $success($msg)
  <font color=$brand_success><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$brand_error><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$brand_warning><b>$msg
!endprocedure

!procedure $primary_scheme()
	FontColor $primary_text
	BorderColor $brand_primary
	BackgroundColor $brand_primary_light
!endprocedure

''
'' Global Default Values
''
skinparam defaultFontName       "Arial"
skinparam defaultFontSize       12
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           10
skinparam ParticipantPadding    40
skinparam BoxPadding            40
skinparam Padding               5
skinparam ArrowColor            $brand_tertiary
skinparam stereotype {
    CBackgroundColor $brand_secondary_light_1
    CBorderColor $brand_secondary_dark_1
    ABackgroundColor $brand_success_light
    ABorderColor $brand_success
    IBackgroundColor $brand_error_light
    IBorderColor $brand_error
    EBackgroundColor $brand_warning_light
    EBorderColor $brand_warning
    NBackgroundColor $brand_info_light
    NBorderColor $brand_info
}
skinparam title {
	FontColor	                 $brand_secondary_dark_1
	BorderColor	                 $brand_secondary_dark_1
	FontSize	    	         20
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor              $brand_secondary
}

skinparam legend {
	BackgroundColor $brand_secondary
	BorderColor $brand_secondary_dark_1
	FontColor $brand_primary_light
}

!startsub swimlane
skinparam swimlane {
	BorderColor $brand_info
	BorderThickness 2
	TitleBackgroundColor $brand_secondary
	TitleFontColor $brand_primary
}
!endsub

!startsub activity

skinparam activity {
	$primary_scheme()
	BarColor $brand_success
	StartColor $brand_info
	EndColor $brand_info
	''
	DiamondBackgroundColor $brand_secondary_light_1
  	DiamondBorderColor $brand_secondary_dark_1
  	DiamondFontColor $secondary_text
}
!endsub

!startsub participant

skinparam participant {
	$primary_scheme()
	ParticipantBorderThickness 2
}
!endsub

!startsub actor

skinparam actor {
	$primary_scheme()
}
!endsub

!startsub arrow

skinparam arrow {
	Thickness 3
	Color $brand_primary
	FontColor $primary_text
}
!endsub

!startsub sequence

skinparam sequence {
	BorderColor $brand_primary
	' For some reason sequence title font color does not pick up from global
	TitleFontColor $brand_primary
	BackgroundColor $brand_primary_light_2
	StartColor $brand_primary
	EndColor $brand_primary
	''
	BoxBackgroundColor $brand_primary_light_2
	BoxBorderColor $brand_secondary_dark_1
	BoxFontColor $brand_secondary_dark_1
	''
	DelayFontColor $brand_secondary_dark_1
	''
	LifeLineBorderColor $brand_primary_light_2
	LifeLineBorderThickness 2
	LifeLineBackgroundColor $brand_primary_light
	''
	GroupBorderColor $brand_secondary_dark_1
	GroupFontColor $brand_secondary_dark_1
	GroupHeaderFontColor $brand_info
	GroupBackgroundColor $brand_primary_light
	GroupBodyBackgroundColor $brand_primary_light_2
	GroupHeaderBackgroundColor $brand_primary_light_2
	''
	DividerBackgroundColor $brand_secondary_dark_1
    DividerBorderColor $brand_secondary_dark_1
    DividerBorderThickness 2
    DividerFontColor $brand_primary_light
	''
	ReferenceBackgroundColor $brand_primary_light_2
	ReferenceBorderColor $brand_secondary_dark_1
	ReferenceFontColor $brand_secondary_dark_1
	ReferenceHeaderFontColor $brand_info
	ReferenceHeaderBackgroundColor $brand_secondary
	''
	StereotypeFontColor $primary_text
}
!endsub

!startsub partition

skinparam partition {
	BorderColor $brand_primary
	FontColor $brand_primary
	BackgroundColor $brand_primary_light_2
}
!endsub

!startsub collections

skinparam collections {
	$primary_scheme()
}
!endsub

!startsub control

skinparam control {
	$primary_scheme()
}
!endsub

!startsub entity

skinparam entity {
	$primary_scheme()
}
!endsub

!startsub boundary

skinparam boundary {
	$primary_scheme()
}
!endsub

!startsub agent

skinparam agent {
	BackgroundColor $brand_warning
	BorderColor $brand_warning_light
	FontColor $brand_secondary_dark_1
}
!endsub

!startsub note

skinparam note {
	BorderThickness 1
	BackgroundColor $brand_info
	BorderColor $brand_info
	FontColor $WHITE
}
!endsub

!startsub artifact

skinparam artifact {
	BackgroundColor $brand_secondary_dark_1
	BorderColor $brand_secondary_dark_2
	FontColor $brand_primary_light
}
!endsub

!startsub component

skinparam component {
	$primary_scheme()
}
!endsub

!startsub interface

skinparam interface {
	BackgroundColor  $brand_error
	BorderColor  $brand_error
	FontColor $brand_secondary_dark_1
}
!endsub

!startsub storage

skinparam storage {
	BackgroundColor $brand_warning
  	BorderColor $brand_warning
	FontColor $warning_text
}
!endsub

!startsub node

skinparam node {
	BackgroundColor  $brand_secondary
	BorderColor $brand_primary_light
	FontColor $brand_primary_light
}
!endsub

!startsub cloud

skinparam cloud {
	BackgroundColor transparent
	BorderColor #F2FCFE
	FontColor $brand_secondary_dark_1
}
!endsub

!startsub database

skinparam database {
	$primary_scheme()
}
!endsub

!startsub class

skinparam class {
	$primary_scheme()
	HeaderBackgroundColor $brand_primary_light
	StereotypeFontColor $brand_secondary_dark_1
	BorderThickness 1
	AttributeFontColor $brand_secondary_dark_1
	AttributeFontSize 11
}
!endsub

!startsub object

skinparam object {
	$primary_scheme()
	StereotypeFontColor $brand_secondary_dark_1
	BorderThickness 1
	AttributeFontColor $secondary_text
	AttributeFontSize 11
}
!endsub

!startsub usecase

skinparam usecase {
	$primary_scheme()
	BorderThickness 2
	StereotypeFontColor $brand_primary
}
!endsub

!startsub rectangle

skinparam rectangle {
	$primary_scheme()
	BackgroundColor $brand_secondary_light_1
	BorderThickness 2
	StereotypeFontColor $brand_primary
}
!endsub

!startsub package

skinparam package {
	BackgroundColor $brand_secondary
  	BorderColor $brand_primary
	FontColor $brand_primary
	BorderThickness 2
}
!endsub

!startsub folder

skinparam folder {
	BackgroundColor $brand_secondary_light_1
  	BorderColor $brand_warning
	FontColor $brand_warning
	BorderThickness 2
}
!endsub

!startsub frame

skinparam frame {
	BackgroundColor $brand_secondary_light_1
  	BorderColor $brand_info
	FontColor $brand_info
	BorderThickness 2
}
!endsub

!startsub state

skinparam state {
	$primary_scheme()
	StartColor $brand_info
	EndColor $brand_info
	AttributeFontColor $secondary_text
	AttributeFontSize 11
}
!endsub

!startsub queue

skinparam queue {
	$primary_scheme()
}
!endsub

!startsub card

skinparam card {
	BackgroundColor $brand_info
	BorderColor $brand_info
	FontColor $info_text
}
!endsub

!startsub file

skinparam file {
	BackgroundColor $brand_secondary_dark_1
	BorderColor $brand_primary_light
	FontColor $brand_primary_light
}
!endsub

!startsub stack

skinparam stack {
	$primary_scheme()
}
!endsub
