#!/bin/bash

if [ "true" = "$DEBUG" ]; then
    env                      # ...showing the environment
    cat "$GITHUB_EVENT_PATH" # ...and the GitHub webhook payload
    set -x                   # ...and script execution.
fi

# Any errors should cause an immediate exit and failure.
set -e

echo "GITHUB_TOKEN: $GITHUB_TOKEN"
echo "GITHUB_ACTOR_EMAIL: $GITHUB_ACTOR_EMAIL"
echo "GITHUB_ACTOR: $GITHUB_ACTOR"
echo "GH_PAGES_BRANCH: $GH_PAGES_BRANCH"
echo "JEKYLL_ENV: $JEKYLL_ENV"
echo "DEBUG: $DEBUG"

# Set input variables
readonly gh_api_token="$GITHUB_TOKEN"
readonly commiter_email="$GITHUB_ACTOR_EMAIL"
readonly committer_name="$GITHUB_ACTOR"
readonly publishing_branch="$GH_PAGES_BRANCH"
readonly jekyll_env="$JEKYLL_ENV"

# Install gems
# Set up git
echo "setup git"
if [ "true" != "$DEBUG" ]; then
    git config user.email "${commiter_email}" || exit $?
    git config user.name "${committer_name}" || exit $?
    git config remote.origin.url "https://x-access-token:${gh_api_token}@github.com/SwedbankPay/swedbank-pay-design-guide-jekyll-theme.git" || exit $?
    git fetch || exit $?
    git checkout -B "$publishing_branch" || exit $?
fi
echo "done that"

# Build project
bundle exec jekyll build JEKYLL_ENV=$jekyll_env --verbose || exit $?

echo "Branch name: $branch_name"
if [ $branch_name = "master" ]; then
    cd _site
    echo "in site"
    git add -a
    git commit -m "Autodeployed"
    echo "commited"
    branch_name="$(git rev-parse --abbrev-ref HEAD)"
    echo "Pushing to $publishing_branch"
    git push --force origin "$publishing_branch" || exit $?
fi
echo "done"
