FROM jekyll/jekyll:4.0.0

RUN apk add --no-cache --no-progress\
    graphviz\
    openjdk8-jre-base\
    fontconfig\
    ttf-dejavu

COPY . .

RUN chmod +x .docker/ci-build-publish

ENTRYPOINT [ ".docker/ci-build-publish" ]