FROM jekyll/jekyll:4.0.0

RUN apk add --no-cache --no-progress\
    graphviz\
    openjdk8-jre-base\
    fontconfig\
    ttf-dejavu

RUN gem install bundler

WORKDIR /srv/jekyll

RUN bundle install

RUN bundle exec jekyll build JEKYLL_ENV=production

WORKDIR /srv/jekyll/_site

RUN git add -a
RUN git commit -m "Autodeployed from Docker"

