#!/bin/bash

mkdir -p /var/jekyll
mkdir -p /srv/jekyll
chown -R jekyll:jekyll /srv/jekyll
chown -R jekyll:jekyll /var/jekyll
chown -R jekyll:jekyll /usr/local/bundle

apt-get update && \
    apt-get install -y \
    git

gem update --system
gem install --force bundler

bundle install

bundle check

exec "$@"
