@startuml "Network"
    !theme swedbankpay from ../assets/

    actor client
    node app
    database db
    queue queue
    cloud cloud
    usecase usecase
    rectangle rectangle
    package package
    folder folder
    frame frame
    card card
    file file

    db -> app
    app -> queue
    queue -> cloud
    cloud <- client
@enduml
